### ISSUE TITLE
acm> does not print in the end of console log

### ISSUE THREAD

**Issue by cuiyanx** [intel/zephyrjs-ide#47] opened 2017-02-15 05:48 UTC
**Issue description**
When I am using ashell command "run" to run my JS code, The command prompt(`acm>`) not in the end of the console window. But I input another ashell command, The command prompt(`acm>`) will be re-displayed in the end of the console window.

**Current behavior**
The command prompt(`acm>`) is in the moddle of my JS code's console logs.
test code: [test-timer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js)
![selection_004](https://cloud.githubusercontent.com/assets/22387607/22966446/24a10214-f39d-11e6-817d-517bbbdde039.png)

**Expected behavior**
displayed in the end of the console window.
test code:
```
for (var i = 0; i < 10; i++) {
  console.log(i);
}
```
![selection_007](https://cloud.githubusercontent.com/assets/22387607/23004253/8b6779a4-f430-11e6-97e2-ca030423a995.png)

**Steps to reproduce**
1. Coding JS script that will output a lot of console logs.
2. Click on Upload button to upload this JS code, It will be saved as temp.dat automatically.
3. Run this temp JS code. `run temp.dat`
4. You will see the command prompt(`acm>`) is in the moddle of my JS code's console logs.

**Zephyr.js IDE version:** `0.8.1 / c9027d6`

**Comment by siovene** [comment] 2017-02-15 08:38
Screenshot please? I don't see this.

I connected to a device and ran the following code on it:
```js
for (var i = 0; i < 100; i++) {
  console.log(i);
}
```

and the `acm>` prompt was always at the end of the output.

**Comment by cuiyanx** [comment] 2017-02-15 08:51
![selection_004](https://cloud.githubusercontent.com/assets/22387607/22966446/24a10214-f39d-11e6-817d-517bbbdde039.png)

**Comment by siovene** [comment] 2017-02-15 08:52
Can you share the code that you used in the editor to generate that output?

**Comment by cuiyanx** [comment] 2017-02-15 08:55
test code:
[test-timer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js)

**Comment by cuiyanx** [comment] 2017-02-17 09:27
@siovene Maybe this issue appears because of delay output console logs with zephyr.js timers. I test [test-pwm.js](https://github.com/01org/zephyr.js/blob/master/tests/test-pwm.js) like this issue.

**Comment by siovene** [comment] 2017-05-08 18:37
Is this still an issue?

**Comment by qiaojingx** [comment] 2017-05-09 06:54
Verified with version v0.13.2-alpha / 02c9ee1. This issue is still reproducible.

`acm>` appears in the result queue, not at the end of console log. Please refer to the screenshot.
![selection_069](https://cloud.githubusercontent.com/assets/19813546/25838632/adc5ad50-34c6-11e7-89b7-7d89ee10bac2.png)

But, `acm>` will print by pressing 'Enter' manually.

**Comment by siovene** [comment] 2017-05-09 07:21
Okay this is because `ashell` is sending data coming from the running up and we have no choice but to append it in the console because we cannot differentiate input coming because the user just typed something, or input coming that way.

@nagineni, does it make sense running an app on the device is asynchronous? I like it this way, but in that case we should mark the app's output so it goes somewhere else in the UI.

Yeah, we meed that protocol...

**Comment by xiaoyu3x** [comment] 2017-09-21 06:54
This issue is reproduced with commit [c5b35be](https://github.com/01org/zephyrjs-ide/commit/c5b35be17d8cc63de91c5c2da4d28308617bf882)

**Comment by xiaoyu3x** [comment] 2018-04-17 08:35
This issue isn't reproduced with commit 02a08ec, so closed it.

**Closed** 2018-04-17 21:15 UTC
Labels: enhancement, webusb
